name: commlayers-front

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:80"
    networks:
      - commlayers_net

networks:
  commlayers_net:
    external: true
    name: commlayers_net
